### ISSUE TITLE
ata.get.items()

### ISSUE THREAD

**Issue by seonghobae** [xluo11/xxIRT#1]
Hi,

I lost a function ata.get.items() in your library. I have to use this, but I can't. Could you recommend alternative methods?

Best,
Seongho

**Comment by xluo11** [comment]
Seongho,

I'm sorry that I changed the function names to make the API more consistent
and modern. Supposing your ATA object is named 'x' and it is solved
successfully, the assembled items can be retrieved from 'x$items'. You
don't need to call ata.get.items(). Use the "as.list" argument to choose a
list or a data frame of assembled items. For more detail, see the
"automated test assembly" section in the documentation:
https://github.com/xluo11/xxIRT#automated-test-assembly


Hope this helps. Let me know if you have other questions.

Thanks,

Xiao
