### ISSUE TITLE
询问

### ISSUE THREAD

**Issue by mengdiW** [xluo11/xxIRT#10]
您好，我是中山大学研二的一名学生，在知网上看到您的论文，对您的论文方向很感兴趣，想深入研究使用神经网络估计IRT参数，您最近还在研究这个方向吗

**Comment by xluo11** [comment]
你就我们就直接在邮箱交流 GitHub上面是公开的

你好 我一直对estimation都感兴趣 我也想过用machine learning 的方法来做estimation 但是一直没时间
你的讲讲你的想法 看看有什么可以帮到的

**Comment by xluo11** [comment]
我的邮箱是xluo1986@gmail.com

**Comment by xluo11** [comment]
off-the-topic in relation to the package itself. move the discussion to email.
