### ISSUE TITLE
The estimation algorithm of IRT model

### ISSUE THREAD

**Issue by badbye** [xluo11/xxIRT#2]
I have found a Python package [pyirt](https://github.com/17zuoye/pyirt/blob/master/pyirt/solver/model.py#L7) , which is using the EM algorithm to do the estimation. Here is the reference: http://www.openirt.com/b-a-h/papers/note9801.pdf

I did not find the reference in your code implementation. According to the code, seems xxIRT and pyirt are using different algorithms. Which one is more popular and robust?

**Comment by xluo11** [comment]
This is my reference: [https://www.amazon.com/Item-Response-Theory-Estimation-Techniques/dp/0824758250](https://www.amazon.com/Item-Response-Theory-Estimation-Techniques/dp/0824758250). To compare two implementations, you can simply conduct a simulation study (see examples in the [Parameter Estimation](https://github.com/xluo11/xxIRT#parameter-estimation) section).

**Comment by badbye** [comment]
Hmmm, this material is not easy to access. Thank you anyway.
