### ISSUE TITLE
rescaled discrimination parameter

### ISSUE THREAD

**Issue by giadasp** [xluo11/xxIRT#5]
I've some doubts about the rescaling term `D` that you use in `$P` and `$I` functions.
In all the othe functions, like `Ii` you use a `D=1` instead when you generate data by `$gendata` or when you use `irt_stats()` you use `D=1.7` (that actually should be 1.702 but I think it's almost the same) .
Why you use a different approach in the two cases?

Thank you for your support.
Giada

**Comment by xluo11** [comment]
I use D=1.7. Can you show me where you see D=1? If `Ii` means `$I()`, then I believe D=1.7.

**Comment by giadasp** [comment]
I'm so sorry, I got confused with another package that I was using simoultaneously with yours!!
Anyway I think that it's better to let the user choose for the preferred `D`.
I'm still waiting for your mail, you can look for my identity also on Linkedin.
I cannot find your address anywhere so I can contact you only by this issue section...
Thank you again for your patience.
Sincerely,
Giada
