### ISSUE TITLE
pulling forms simultaneously

### ISSUE THREAD

**Issue by hisari87** [xluo11/xxIRT#6]
Hi Xluo,

I would like to pull 3 different forms at the same time, but form 1 has to maximize the information at theta point of -1,  form 2 has to maximize the information at the theta point of 0, and form 3 has to maximize the information at the theta point of 1. In the codes, you showed an example, but it's maximizing the information over an interval for all forms (-1,1). How can I do that?

**Comment by xluo11** [comment]
First, create the ata as usual, say 10 items each form: `x <- ata(items, 3, len=10, maxselect=1)`. Second, set a relative objective for each form:
`x <- ata_obj_relative(x, -1, "max", forms=1 )`,
`x <- ata_obj_relative(x, 0, "max", forms=2 )`,
`x <- ata_obj_relative(x, 1, "max", forms=3)`.
Last, solve it: `x <- ata_solve(x)`
Let me know if it works.

**Comment by hisari87** [comment]
Thank you so much! It worked when I did max_use=1 instead of maxselect=1! 

My last question is that; would it be possible to pull multiple forms with different test lengths and maximize information at different theta points? For example, form 1 will have 5 items and maximize the info at -1 theta point, and form 2 will have 15 items and maximize the info at 0 theta point, and finally form 3 will have 20 items and maximize the info at theta point of 1.

Thanks in advance!

**Comment by xluo11** [comment]
Yes. Just add test length as a regular constraint.
First, create the ATA without setting the length: `x <- ata(items, 3, max_use=1)`
Second, add objective function for each form:
`x <- ata_obj_relative(x, -1, "max", forms=1)`
`x <- ata_obj_relative(x, 0, "max", forms=2)`
`x <- ata_obj_relative(x,  1, "max", forms=3)`
Third, add test length constraints:
`x <- add_constraint(x, 1, min=5, max=5, forms=1)`
`x <- add_constraint(x, 1, min=15, max=15, forms=2)`
`x <- add_constraint(x, 1, min=20, max=20, forms=3)`
Last, solve it:
`x <- ata_solve(x)`

Let me know if this works

**Comment by hisari87** [comment]
When I say "ata_obj_relative" instead of "add_constraint", it worked well!
Thanks a lot!
